# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0116ca0876591b8f8097485bac8b0ea704d391b6c4b846261d8b3f66c256c47f7bdfa75665bc20efacc880f5d9a83f94a256fea5691275ddfb3ff3bdb90b812a

test:
  secret_key_base: 3203b27770c047b14427a68edb18311b7daadcbb1a99074d4749197a78bdff96b86b431c4baa7c0c915c821d798b1634d5bb1a2341b7bbc66ccead51de4ef812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
